# Generated by Django 5.2.7 on 2025-12-08 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='bioavailability_score',
            field=models.CharField(blank=True, help_text='e.g. High, Low, Poor', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserSupplementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dosage', models.FloatField(help_text='Amount taken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_supplement_logs', to=settings.AUTH_USER_MODEL)),
                ('user_supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_supplement_logs', to='supplements.usersupplement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
