# Generated by Django 5.2.9 on 2026-01-19 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0002_alter_exercise_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for frontend', max_length=50)),
                ('category', models.CharField(choices=[('workout_count', 'Workout Count'), ('workout_streak', 'Workout Streak'), ('pr_weight', 'Personal Record Weight'), ('pr_one_rep_max', 'Personal Record 1RM'), ('total_volume', 'Total Volume'), ('exercise_count', 'Exercise Count'), ('muscle_volume', 'Muscle Volume'), ('consistency', 'Consistency')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('requirement_value', models.DecimalField(decimal_places=2, help_text="The value needed to earn this achievement (e.g., 100 for '100 workouts', 60 for '60kg bench')", max_digits=10)),
                ('muscle_group', models.CharField(blank=True, help_text='Required for muscle-based achievements', max_length=20, null=True)),
                ('points', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden achievements are revealed when earned')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(blank=True, help_text='Required for PR-based achievements', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='exercise.exercise')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['category', 'order', 'requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseStatistics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('weight_percentiles', models.JSONField(default=dict)),
                ('one_rm_percentiles', models.JSONField(default=dict)),
                ('volume_percentiles', models.JSONField(default=dict)),
                ('average_weight', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('average_one_rm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('median_weight', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('median_one_rm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='exercise.exercise')),
            ],
            options={
                'verbose_name': 'Exercise Statistics',
                'verbose_name_plural': 'Exercise Statistics',
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_workouts', models.PositiveIntegerField(default=0)),
                ('total_workout_duration', models.PositiveIntegerField(default=0, help_text='Total seconds')),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sets', models.PositiveIntegerField(default=0)),
                ('total_reps', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current workout streak in days')),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='Longest workout streak ever')),
                ('last_workout_date', models.DateField(blank=True, null=True)),
                ('total_achievements', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('total_prs', models.PositiveIntegerField(default=0, help_text='Total personal records set')),
                ('prs_this_month', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Statistics',
                'verbose_name_plural': 'User Statistics',
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('best_weight', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('best_weight_reps', models.PositiveIntegerField(default=0, help_text='Reps done at best weight')),
                ('best_weight_date', models.DateTimeField(blank=True, null=True)),
                ('best_one_rep_max', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('best_one_rep_max_weight', models.DecimalField(decimal_places=2, default=0, help_text='Weight used to calculate best 1RM', max_digits=7)),
                ('best_one_rep_max_reps', models.PositiveIntegerField(default=0, help_text='Reps used to calculate best 1RM')),
                ('best_one_rep_max_date', models.DateTimeField(blank=True, null=True)),
                ('best_set_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('best_set_volume_date', models.DateTimeField(blank=True, null=True)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sets', models.PositiveIntegerField(default=0)),
                ('total_reps', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='exercise.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Record',
                'verbose_name_plural': 'Personal Records',
                'ordering': ['exercise__name'],
                'unique_together': {('user', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('current_progress', models.DecimalField(decimal_places=2, default=0, help_text='Current progress towards achievement', max_digits=10)),
                ('earned_value', models.DecimalField(blank=True, decimal_places=2, help_text='The actual value when earned (e.g., actual weight lifted)', max_digits=10, null=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
