from os import name
from django.db import models

# Create your models here.

from core.models import TimestampedModel
from user.models import CustomUser


class Exercise(TimestampedModel):

    ## id auto generated by Model.model
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    instructions = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='exercises/', blank=True, null=True)
    video_url = models.URLField(blank=True, null=True)

    MUSCLE_GROUPS = [
        # Chest
        ('chest', 'Chest'),

        # Shoulders
        ('shoulders', 'Shoulders'),

        # Arms
        ('biceps', 'Biceps'),
        ('triceps', 'Triceps'),
        ('forearms', 'Forearms'),

        # Back
        ('lats', 'Back – Lats'),
        ('traps', 'Back – Traps'),
        ('lower_back', 'Back – Lower Back'),

        # Legs
        ('quads', 'Legs – Quads'),
        ('hamstrings', 'Legs – Hamstrings'),
        ('glutes', 'Legs – Glutes'),
        ('calves', 'Legs – Calves'),

        # Core
        ('abs', 'Core – Abs'),
        ('obliques', 'Core – Obliques'),
    ]

    primary_muscle = models.CharField(max_length=255, choices=MUSCLE_GROUPS)
    secondary_muscles = models.JSONField(default=list, blank=True, null=True)

    EQUIPMENT_TYPES = [
        ('bodyweight', 'Bodyweight'),
        ('barbell', 'Barbell'),
        ('dumbbell', 'Dumbbell'),
        ('machine', 'Machine'),
        ('cable', 'Cable'),
        ('resistance_band', 'Resistance Band'),
        ('kettlebell', 'Kettlebell'),
        ('treadmill', 'Treadmill'),
        ('other', 'Other'),
    ]

    equipment_type = models.CharField(max_length=255, choices=EQUIPMENT_TYPES)

    def __str__(self): # __str__ is a special method in Python that is used to return a string representation of the object.
        return self.name ## self.name is the name of the exercise.


class ExerciseSet(TimestampedModel):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    set = models.PositiveIntegerField(default=0)
    rep = models.PositiveIntegerField(default=0)
    weight = models.PositiveIntegerField(default=0)
    rest_time_before_set = models.PositiveIntegerField(default=0)

