from os import name
from django.db import models
import os
from django.utils.text import slugify

# Create your models here.

from core.models import TimestampedModel
from user.models import CustomUser

def exercise_image_upload_path(instance, filename):
    # Get the file extension
    ext = filename.split('.')[-1]
    # Create the filename based on the exercise name
    filename = f"{slugify(instance.name)}.{ext}"
    # Return the full path
    return os.path.join('exercises', filename)


class Exercise(TimestampedModel):

    ## id auto generated by Model.model
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    instructions = models.TextField(blank=True, null=True)
    safety_tips = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to=exercise_image_upload_path, blank=True, null=True)
    video_url = models.URLField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    MUSCLE_GROUPS = [
        # Chest
        ('chest', 'Chest'),

        # Shoulders
        ('shoulders', 'Shoulders'),

        # Arms
        ('biceps', 'Biceps'),
        ('triceps', 'Triceps'),
        ('forearms', 'Forearms'),

        # Back
        ('lats', 'Back – Lats'),
        ('traps', 'Back – Traps'),
        ('lower_back', 'Back – Lower Back'),

        # Legs
        ('quads', 'Legs – Quads'),
        ('hamstrings', 'Legs – Hamstrings'),
        ('glutes', 'Legs – Glutes'),
        ('calves', 'Legs – Calves'),

        # Core
        ('abs', 'Core – Abs'),
        ('obliques', 'Core – Obliques'),
        
        # Other
        ('abductors', 'Abductors'),
        ('adductors', 'Adductors'),
    ]

    primary_muscle = models.CharField(max_length=255, choices=MUSCLE_GROUPS)
    secondary_muscles = models.JSONField(default=list, blank=True, null=True)

    EQUIPMENT_TYPES = [
        ('bodyweight', 'Bodyweight'),
        ('barbell', 'Barbell'),
        ('dumbbell', 'Dumbbell'),
        ('machine', 'Machine'),
        ('cable', 'Cable'),
        ('resistance_band', 'Resistance Band'),
        ('kettlebell', 'Kettlebell'),
        ('treadmill', 'Treadmill'),
        ('stationary_bike', 'Stationary Bike'),
        ('elliptical', 'Elliptical'),
        ('rowing_machine', 'Rowing Machine'),
        ('bicycle', 'Bicycle'),
        ('ez_bar', 'EZ Bar'),
        ('dip_bars', 'Dip Bars'),
        ('pull_up_bar', 'Pull Up Bar'),
        ('preacher_bench', 'Preacher Bench'),
        ('other', 'Other'),
    ]

    equipment_type = models.CharField(max_length=255, choices=EQUIPMENT_TYPES)
    
    CATEGORY_CHOICES = [
        ('compound', 'Compound'),
        ('isolation', 'Isolation'),
        ('cardio', 'Cardio'),
        ('stability', 'Stability'),
    ]
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='compound')
    
    DIFFICULTY_CHOICES = [
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    ]
    difficulty_level = models.CharField(max_length=50, choices=DIFFICULTY_CHOICES, default='beginner')

    def __str__(self): # __str__ is a special method in Python that is used to return a string representation of the object.
        return self.name ## self.name is the name of the exercise.
