# Generated by Django 5.2.7 on 2025-12-18 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_templateworkout_templateworkoutexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
