# Generated by Django 5.2.7 on 2025-12-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workout_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_rest_day',
            field=models.BooleanField(default=False),
        ),
    ]
