# Generated by Django 5.2.7 on 2025-12-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_workout_is_rest_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateworkout',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
