# Generated by Django 5.2.7 on 2025-12-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_templateworkout_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='one_rep_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
