# Generated by Django 5.2.7 on 2025-12-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_workoutexercise_one_rep_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('INTENSITY_GUIDELINES', 'Intensity Guidelines'), ('PROTEIN_SYNTHESIS', 'Protein Synthesis'), ('MUSCLE_GROUPS', 'Muscle Groups'), ('MUSCLE_RECOVERY', 'Muscle Recovery'), ('REST_PERIODS', 'Rest Periods'), ('TRAINING_FREQUENCY', 'Training Frequency')], max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source_title', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('source_authors', models.JSONField(blank=True, default=list)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('evidence_level', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('applicable_muscle_groups', models.JSONField(blank=True, default=list)),
                ('applicable_exercise_types', models.JSONField(blank=True, default=list)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
