# Generated by Django 5.2.7 on 2025-12-18 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_workout_calories_burned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('lats', 'Back – Lats'), ('traps', 'Back – Traps'), ('lower_back', 'Back – Lower Back'), ('quads', 'Legs – Quads'), ('hamstrings', 'Legs – Hamstrings'), ('glutes', 'Legs – Glutes'), ('calves', 'Legs – Calves'), ('abs', 'Core – Abs'), ('obliques', 'Core – Obliques'), ('abductors', 'Abductors'), ('adductors', 'Adductors')], max_length=50)),
                ('fatigue_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_sets', models.PositiveIntegerField(default=0)),
                ('recovery_hours', models.PositiveIntegerField(default=24)),
                ('recovery_until', models.DateTimeField(blank=True, null=True)),
                ('is_recovered', models.BooleanField(default=False)),
                ('source_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recovery_until'],
                'unique_together': {('user', 'muscle_group', 'source_workout')},
            },
        ),
    ]
