# Generated by Django 5.2.7 on 2025-12-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_musclerecovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingresearch',
            name='category',
            field=models.CharField(choices=[('INTENSITY_GUIDELINES', 'Intensity Guidelines'), ('PROTEIN_SYNTHESIS', 'Protein Synthesis'), ('MUSCLE_GROUPS', 'Muscle Groups'), ('MUSCLE_RECOVERY', 'Muscle Recovery'), ('REST_PERIODS', 'Rest Periods'), ('TRAINING_FREQUENCY', 'Training Frequency'), ('BODY_MEASUREMENTS', 'Body Measurements')], max_length=50),
        ),
    ]
