# Generated by Django 5.2.9 on 2025-12-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_alter_trainingresearch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='concentric_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='eccentric_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='total_tut',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
