# Generated by Django 5.2.9 on 2025-12-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_exerciseset_concentric_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='total_tut',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
