# Generated by Django 5.2.9 on 2025-12-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_alter_exerciseset_total_tut'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='rest_timer_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
