# Generated by Django 5.2.9 on 2025-12-30 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0013_workout_rest_timer_paused_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutMuscleRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('lats', 'Back – Lats'), ('traps', 'Back – Traps'), ('lower_back', 'Back – Lower Back'), ('quads', 'Legs – Quads'), ('hamstrings', 'Legs – Hamstrings'), ('glutes', 'Legs – Glutes'), ('calves', 'Legs – Calves'), ('abs', 'Core – Abs'), ('obliques', 'Core – Obliques'), ('abductors', 'Abductors'), ('adductors', 'Adductors')], max_length=50)),
                ('condition', models.CharField(choices=[('pre', 'Pre-Workout'), ('post', 'Post-Workout')], max_length=10)),
                ('recovery_progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_recovery_records', to='workout.workout')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'workout', 'muscle_group', 'condition')},
            },
        ),
    ]
