# Generated by Django 5.2.9 on 2026-01-06 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0014_workoutmusclerecovery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CNSRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cns_load', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('recovery_hours', models.PositiveIntegerField(default=24)),
                ('recovery_until', models.DateTimeField(blank=True, null=True)),
                ('is_recovered', models.BooleanField(default=False)),
                ('source_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recovery_until'],
                'unique_together': {('user', 'source_workout')},
            },
        ),
    ]
