# Generated by Django 5.2.7 on 2025-11-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('safety_tips', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('primary_muscle', models.CharField(choices=[('chest', 'Chest'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('lats', 'Back – Lats'), ('traps', 'Back – Traps'), ('lower_back', 'Back – Lower Back'), ('quads', 'Legs – Quads'), ('hamstrings', 'Legs – Hamstrings'), ('glutes', 'Legs – Glutes'), ('calves', 'Legs – Calves'), ('abs', 'Core – Abs'), ('obliques', 'Core – Obliques'), ('abductors', 'Abductors'), ('adductors', 'Adductors')], max_length=255)),
                ('secondary_muscles', models.JSONField(blank=True, default=list, null=True)),
                ('equipment_type', models.CharField(choices=[('bodyweight', 'Bodyweight'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('resistance_band', 'Resistance Band'), ('kettlebell', 'Kettlebell'), ('treadmill', 'Treadmill'), ('stationary_bike', 'Stationary Bike'), ('elliptical', 'Elliptical'), ('rowing_machine', 'Rowing Machine'), ('bicycle', 'Bicycle'), ('ez_bar', 'EZ Bar'), ('dip_bars', 'Dip Bars'), ('pull_up_bar', 'Pull Up Bar'), ('preacher_bench', 'Preacher Bench'), ('other', 'Other')], max_length=255)),
                ('category', models.CharField(choices=[('compound', 'Compound'), ('isolation', 'Isolation'), ('cardio', 'Cardio'), ('stability', 'Stability')], default='compound', max_length=50)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
