# Generated by Django 5.2.7 on 2025-12-16 21:50

import exercise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=exercise.models.exercise_image_upload_path),
        ),
    ]
