"""
Django settings for utrack project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
import warnings
import environ
from pathlib import Path

# Initialize environ
env = environ.Env(
  
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# --- Configuration ---

# 1. Core Settings (Typed automatically)
SECRET_KEY = env('SECRET_KEY')





# 4. Apple & EC2 Settings
APPLE_KEY_ID = env('APPLE_KEY_ID')
APPLE_TEAM_ID = env('APPLE_TEAM_ID')
APPLE_CLIENT_ID = env('APPLE_CLIENT_ID')
APPLE_PRIVATE_KEY = env('APPLE_PRIVATE_KEY').replace('\\n', '\n') # Fixes newline issues in keys
EC2_ELASTIC_IP = env('EC2_ELASTIC_IP')
POSTGRES_USER = env('POSTGRES_USER', default="")
POSTGRES_PASSWORD = env('POSTGRES_PASSWORD', default="")
POSTGRES_DB = env('POSTGRES_DB', default="")
LOCALHOST = env('LOCALHOST')
# Suppress specific warnings from dj_rest_auth regarding allauth deprecations
warnings.filterwarnings('ignore', message='.*app_settings.USERNAME_REQUIRED is deprecated.*')
warnings.filterwarnings('ignore', message='.*app_settings.EMAIL_REQUIRED is deprecated.*')

# DB_HOST and DB_PORT are set conditionally based on LOCALHOST and DATABASE_URL
# Initialize with defaults to avoid errors if not set in .env
DB_HOST = env('DB_HOST', default='localhost')
DB_PORT = env('DB_PORT', default='5432')
# Build DATABASE_URL if not already set and we have the components
if POSTGRES_USER and POSTGRES_PASSWORD and POSTGRES_DB:
    # Check if DATABASE_URL is already set (from .env), if not, build it
    try:
        DATABASE_URL = env('DATABASE_URL')
    except:
        DATABASE_URL = f"postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{DB_HOST}:{DB_PORT}/{POSTGRES_DB}"
else:
    DATABASE_URL = None

if LOCALHOST == 'True' and not DATABASE_URL:
    DEBUG = True
    ALLOWED_HOSTS = ['*']
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif LOCALHOST == 'True' and DATABASE_URL: # Localhost is True and DATABASE_URL is set WHICH MEANS WE ARE IN DOCKER COMPOSE
    DEBUG = True
    ALLOWED_HOSTS = ['*']
    DB_HOST = 'db' # because we are in docker compose
    DB_PORT = 5432 # because we are in docker compose
    DATABASE_URL = f"postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{DB_HOST}:{DB_PORT}/{POSTGRES_DB}"

    DATABASES = {
        'default': env.db('DATABASE_URL')
    }

elif LOCALHOST == 'False' and DATABASE_URL: # Localhost is False and DATABASE_URL is set - could be Docker or EC2
    DEBUG = False
    ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])
    # Check if we're in Docker (DATABASE_URL contains 'db:5432') or EC2 manual install
    if 'db:5432' in DATABASE_URL:
        # We're in Docker, use 'db' as host
        DB_HOST = 'db'
        DB_PORT = 5432
    else:
        # We're in EC2 manual install, use env values
        DB_HOST = env('DB_HOST', default='localhost')
        DB_PORT = env('DB_PORT', default='5432')
    DATABASES = {
        'default': env.db('DATABASE_URL')
    }
    CSRF_TRUSTED_ORIGINS = ['https://api.utrack.irfanemreutkan.com'] 
elif LOCALHOST == 'False' and not DATABASE_URL:
    raise ValueError("DATABASE_URL is not set")
else:
    raise ValueError("LOCALHOST is not set", LOCALHOST, DATABASE_URL)
    


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'user.CustomUser'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders', # Add corsheaders
    'core',
    'rest_framework',
    'rest_framework.authtoken', # <--- Add this line
    'user',
    'exercise', # Add exercise app
    'workout', # Add workout app
    'supplements', # Add supplements app
    'body_measurements', # Add body measurements app
    'achievements', # Add achievements app
    'django.contrib.sites',       # Required by allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Add CorsMiddleware at the top
    'utrack.middleware.RequestResponseLogMiddleware', # Add logging middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware', 
]

ROOT_URLCONF = 'utrack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'utrack.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization          
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Images, uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True # For dev, allow everyone. Safer than listing specific IPs if you move around.

# CSRF Settings

# Add Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth Configuration (matches your CustomUser email-only setup)
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional' # or 'mandatory'

# Social Account Providers
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'apple': {
        'APP': {
            # Your App ID (Bundle ID) from Apple Developer Console
            'client_id': os.environ.get('APPLE_CLIENT_ID'),
            
            # The Key ID (from the .p8 file details in Apple Developer Console)
            'secret': os.environ.get('APPLE_KEY_ID'),
            
            # Your Apple Team ID
            'key': os.environ.get('APPLE_TEAM_ID'),
            
            # The contents of the .p8 private key file you downloaded from Apple
            'certificate_key': os.environ.get('APPLE_PRIVATE_KEY')
        }
    }
}

# REST Framework Config (update existing)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication', # Optional, for cookie auth
    ),
    # Rate limiting/throttling configuration
    'DEFAULT_THROTTLE_CLASSES': [
        'utrack.throttles.AnonBurstRateThrottle',
        'utrack.throttles.AnonSustainedRateThrottle',
        'utrack.throttles.BurstRateThrottle',
        'utrack.throttles.SustainedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Anonymous users
        'anon_burst': '10/minute',      # 10 requests per minute for anonymous users
        'anon_sustained': '100/hour',    # 100 requests per hour for anonymous users
        
        # Authenticated users (FREE)
        'burst': '60/minute',            # 60 requests per minute
        'sustained': '1000/hour',        # 1000 requests per hour
        
        # PRO users (higher limits)
        'pro_user': '200/minute',        # 200 requests per minute for PRO users
        
        # Specific endpoints
        'login': '5/minute',             # 5 login attempts per minute (prevent brute force)
        'registration': '3/hour',        # 3 registrations per hour per IP
        'password_reset': '3/hour',      # 3 password reset requests per hour
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
}

# Use JWTs with dj-rest-auth
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False, # <--- Add this line to return refresh token in body
}

SITE_ID = 1

# Logging Configuration
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)  # Create logs directory if it doesn't exist

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'request': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'file_errors': {
            'level': 'ERROR',
            'class': 'utrack.logging_handlers.WindowsSafeRotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 10,  # Keep 10 backup files
            'formatter': 'verbose',
        },
        'file_info': {
            'level': 'INFO',
            'class': 'utrack.logging_handlers.WindowsSafeRotatingFileHandler',
            'filename': LOGS_DIR / 'info.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,  # Keep 5 backup files
            'formatter': 'simple',
        },
        'file_requests': {
            'level': 'INFO',
            'class': 'utrack.logging_handlers.WindowsSafeRotatingFileHandler',
            'filename': LOGS_DIR / 'requests.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,  # Keep 5 backup files
            'formatter': 'request',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'console_debug': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file_info', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file_errors', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['file_info', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'utrack': {
            'handlers': ['file_info', 'file_errors', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'utrack.requests': {
            'handlers': ['file_requests', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'workout': {
            'handlers': ['file_info', 'file_errors', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'user': {
            'handlers': ['file_info', 'file_errors', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'exercise': {
            'handlers': ['file_info', 'file_errors', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['file_info', 'file_errors', 'console'],
        'level': 'INFO',
    },
}
