# Generated by Django 5.2.7 on 2025-12-20 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('waist', models.DecimalField(decimal_places=2, help_text='Waist measurement in cm', max_digits=5)),
                ('neck', models.DecimalField(decimal_places=2, help_text='Neck measurement in cm', max_digits=5)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, help_text='Hips measurement in cm (required for women)', max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated body fat % using US Navy method', max_digits=5, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Gender for body fat calculation', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
