# Generated by Django 5.2.7 on 2025-12-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='body_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body weight in kg for calorie calculations', max_digits=5, null=True),
        ),
    ]
