# Generated by Django 5.2.9 on 2026-01-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_weighthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Whether user has active PRO subscription'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pro_until',
            field=models.DateTimeField(blank=True, help_text='PRO subscription expiration date', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_id',
            field=models.CharField(blank=True, help_text='Payment provider subscription ID (Stripe, RevenueCat, etc.)', max_length=255),
        ),
    ]
